# Generated by Django 6.0.4 on 2026-04-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15, unique=True, verbose_name='Numéro de téléphone')),
                ('nom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('equipe', models.CharField(blank=True, max_length=50, verbose_name='Équipe (Mixx/Top Image)')),
                ('team', models.CharField(blank=True, max_length=50, verbose_name='Team (TEAMSEYDI, etc.)')),
                ('est_opener', models.BooleanField(default=False, verbose_name='Est opener')),
                ('est_animateur', models.BooleanField(default=False, verbose_name='Est animateur')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CreationMarchand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_marchand', models.CharField(max_length=15, unique=True, verbose_name='Numéro marchand')),
                ('nom_structure', models.CharField(blank=True, max_length=200, verbose_name='Nom structure')),
                ('type_structure', models.CharField(blank=True, max_length=50, verbose_name='Type structure')),
                ('profil_marchand', models.CharField(blank=True, max_length=50, verbose_name='Profil marchand')),
                ('equipe', models.CharField(blank=True, max_length=50, verbose_name='Équipe')),
                ('team', models.CharField(blank=True, max_length=50, verbose_name='Team')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Région')),
                ('departement', models.CharField(blank=True, max_length=100, verbose_name='Département')),
                ('date_soumission', models.DateTimeField(verbose_name='Date de soumission')),
                ('date_activite', models.DateField(verbose_name="Date d'activité")),
                ('opener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creations', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Création marchand',
                'verbose_name_plural': 'Créations marchands',
                'ordering': ['-date_activite'],
            },
        ),
        migrations.CreateModel(
            name='SuiviMarchand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_marchand', models.CharField(max_length=15, verbose_name='Numéro marchand')),
                ('numero_client', models.CharField(max_length=15, verbose_name='Numéro client')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant')),
                ('application_paiement', models.CharField(max_length=50, verbose_name='Application paiement')),
                ('profil_marchand', models.CharField(blank=True, max_length=50, verbose_name='Profil marchand')),
                ('type_structure', models.CharField(blank=True, max_length=50, verbose_name='Type structure')),
                ('date_soumission', models.DateTimeField(verbose_name='Date de soumission')),
                ('date_activite', models.DateField(verbose_name="Date d'activité")),
                ('animateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Suivi marchand',
                'verbose_name_plural': 'Suivis marchands',
                'ordering': ['-date_activite'],
            },
        ),
    ]
